CREATE TABLE Continent (
    CONTINENT_NAME varchar(30),
    PRIMARY KEY (CONTINENT_NAME)
);

CREATE TABLE Country (
    COUNTRY_NAME varchar(30),
    CONTINENT_NAME varchar(30),
    PRIMARY KEY (COUNTRY_NAME),
    FOREIGN KEY (CONTINENT_NAME) REFERENCES Continent(CONTINENT_NAME) ON DELETE CASCADE
);

CREATE TABLE City (
    CITY_NAME varchar(30),
    COUNTRY_NAME varchar(30),
    PRIMARY KEY (CITY_NAME, COUNTRY_NAME),
    FOREIGN KEY (COUNTRY_NAME) REFERENCES Country(COUNTRY_NAME) ON DELETE CASCADE
);